name: Mirror to client repo

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # ❗ prevents github-actions bot token

      - name: Mirror to client repo
        env:
          PAT: ${{ secrets.CLIENT_TOKEN }}
          CLIENT_REPO: "digitalwealth38-lab/DigitalWealth"
        run: |
          git config --global user.name "AitezazAhmed"
          git config --global user.email "stoneghold4103@gmail.com"

          echo "Adding client remote..."
          git remote add client https://AitezazAhmed:${PAT}@github.com/${CLIENT_REPO}.git
          git fetch client || echo "No client branch yet"
          echo "Pushing to client..."
          git push client main --force
