name: Mirror to client repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Push to client repo
        env:
          CLIENT_REPO: "digitalwealth38-lab/DigitalWealth"
          CLIENT_TOKEN: ${{ secrets.CLIENT_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Add client repo as remote
          git remote add client https://${CLIENT_TOKEN}@github.com/${CLIENT_REPO}.git

          # Push changes forcefully to client repo
          git push client main --force
